### ISSUE TITLE
Sync Failed

### ISSUE THREAD

**Issue by JayTheLegend** [iPlatform-ZA/backend-developer-assessment#4]
Hi Pieter

I have done both of the assessments but I do seem to have problem to do a pull request. I can create all the files manually, but that seems to defeat the object of the exercise. I tried using the Gui interface from github and it says that I do not have permission to push my changes. I then tried doing it through command line and it tels me that I need to make sure I have the correct access rights. Furthermore I tried different URL's as well to no success.

Is it possible for you to double check the permissions on your side or am I missing something?

Kind regards
Henning

**Comment by pieter-iplatform** [comment]
Hi Henning,

You will not have access to push to our repository, but you should be able
to send us a pull request. Other candidates have sent us pull requests.

Alternatively please send me a link to your repository and I'll have a look
at the code from your repository.

Thanks
Pieter
